### ISSUE TITLE
Implement to run the table scripts, and seeds to a dynamodb in a AWS region

### ISSUE THREAD

**Issue by AshanFernando** [99xt/serverless-dynamodb-local#10]
Implement support to run the table scripts, and seeds to a dynamodb in a AWS region so that the same table creation scripts and seeds can be used to update a AWS dynamodb database running inside AWS

sls dynamodb tables aws-init(other options)
sls dynamodb seeds aws-run(other options)

**Comment by AshanFernando** [comment]
Implemented

**Comment by mattfysh** [comment]
@AshanFernando where can I find this implementation? thanks!

**Comment by AshanFernando** [comment]
@mattfysh I original implemented this long time ago, added with the following PR
https://github.com/99xt/serverless-dynamodb-local/pull/33/files
Where we used https://github.com/99xt/dynamodb-migrations package to do the job. Lately this dependency was removed also losing the feature.

**Comment by mattfysh** [comment]
I ended up with something like this:

```javascript
const AWS = require('aws-sdk');
AWS.config.update({region: 'ap-southeast-2'});

const seeder = require('serverless-dynamodb-local/src/seeder');
const doc = new AWS.DynamoDB.DocumentClient();

const source = {
	table: 'events',
	sources: ['./seed/events.json'],
};

seeder.locateSeeds(source.sources)
	.then(seeds => seeder.writeSeeds(doc, source.table, seeds));
```

**Comment by moseley** [comment]
Took me some time to figure this out, so in case anyone else comes across this you can use the following command.
`sls dynamodb seed --seed=domain --online`
In my case I also need to specify the stage and region as well as using the default AWS credentials.
