### ISSUE TITLE
Migrations not made

### ISSUE THREAD

**Issue by kenjinp** [99xt/serverless-dynamodb-local#118]
In the lastest version (0.2.23) running with sls offline plugin: 
` sls dynamodb start --migrate`
or
`sls offline start`
or 
`sls offline start --migrate`

does not trigger migrations, and it seems, there's no way to migrate the db anymore.

I was able to fix this problem by going back to the previous version (0.2.22)

**Comment by AshanFernando** [comment]
@kenjinp Thanks for pointing it out. We have added a new update in version 0.2.24 with a fix. Let us know if its fixed so that we can close the issue.

**Comment by kenjinp** [comment]
Hey @AshanFernando I can confirm it's working. Thanks very much for your help!
