### ISSUE TITLE
Error 'options is not defined'

### ISSUE THREAD

**Issue by cdelgadob** [99xt/serverless-dynamodb-local#120]
Since latest version (0.2.23), an error showing 'options is not defined' is fired when started with any sls command.

Workaround: Reverting to 0.2.22 solves the problem

**Comment by AntonioAngelino** [comment]
Same here.

**Comment by AshanFernando** [comment]
We will have a look at the issue ASAP

**Comment by AshanFernando** [comment]
Updated the NPM version 0.2.24 with the fix by @ChristopheBougere 
@cdelgadob @AntonioAngelino Will you be able to verify its working to close the issue?

**Comment by AntonioAngelino** [comment]
Works like a charm. Thank you @AshanFernando !

**Comment by cdelgadob** [comment]
Solved in version 0.2.24, closing issue. Thanks @AshanFernando
