### ISSUE TITLE
Unexpected key 'TimeToLiveSpecification' found in params

### ISSUE THREAD

**Issue by andreimc** [99xt/serverless-dynamodb-local#131]
https://github.com/serverless/serverless/issues/4250

**Comment by sarneetk** [comment]
I am also facing this issue, when trying to start local dynamo:

`UnexpectedParameter: Unexpected key 'TimeToLiveSpecification' found in params`

Was this issue resolved?

**Comment by GerryFudd** [comment]
I am seeing this issue as well.  I added the following to the "CreateTable" entry of 
apis/dynamodb-2012-08-10.min.json
in my node_modules:

          "TimeToLiveSpecification": {
            "type": "structure",
            "required": [
              "AttributeName",
              "Enabled"
            ],
            "members": {
              "AttributeName": {},
              "Enabled": {
                "type": "boolean"
              }
            }
          }

This allows me to run dynamodb locally.  I assume that you would want a similar entry in the table update for it to work properly, but it does seem to be an unresolved issue.

**Comment by revelfire** [comment]
I'm wondering why this issue is closed when it is unresolved.

I'm using 2017-01-24 (1.11.86)

And this just started happening 'out of the blue'.
```
let tableMeta = {
      TableName: "forecast",
      KeySchema: [
        {
          AttributeName: "forecast_hash",
          KeyType: 'HASH'
        }
      ],
      AttributeDefinitions: [
        {
          AttributeName: "forecast_hash",
          AttributeType: 'S'
        }
      ],
      TimeToLiveDescription: {
        AttributeName: "deleteAfter",
        TimeToLiveStatus: "ENABLED"
      },
      ProvisionedThroughput: {
        ReadCapacityUnits: 1,
        WriteCapacityUnits: 1
      },
      StreamSpecification: {
        StreamEnabled: false
      }
    };
```
 
results in

```
  message: 'Unexpected key \'TimeToLiveDescription\' found in params',
  code: 'UnexpectedParameter',
  time: 2018-05-30T14:22:09.380Z 
```
