### ISSUE TITLE
Using a variable to define dynamodb in serverless.yml doesn't work

### ISSUE THREAD

**Issue by danbovey** [99xt/serverless-dynamodb-local#141]
**Actual Behaviour**

Variables passed to `dynamodb` in `custom` are stored literally. Because the plugin saves the config in the constructor, variables used in `serverless.yml` haven't been parsed yet.

**Expected Behaviour**

Variables passed to `dynamodb` in `custom` are parsed, so that we can create dynamic config, or pass seed data from one file if we have many services in one project.

The config should be loaded outside of the constructor when it is needed, as discussed here https://github.com/serverless/serverless/issues/4244#issuecomment-328557594.

**Steps to reproduce it**

My dynamodb config in my serverless.yml is

```yml
dynamodb: ${file(../database/dynamodb.yml):dynamodb}
```

Logging `this.config` in the constructor shows the config is being stored as literally the string `dynamodb: ${file(../database/dynamodb.yml):dynamodb}`.

**Would you like to work on the issue?**

Submitting a PR today.

**Comment by jasonlimantoro** [comment]
Still experiencing this issue:

https://github.com/99xt/serverless-dynamodb-local/pull/142#issuecomment-502334297
