### ISSUE TITLE
dynamodb noStart - fails on attempt to create existing tables

### ISSUE THREAD

**Issue by mvayngrib** [99xt/serverless-dynamodb-local#144]
I run dynamodb in a docker container (using localstack), so i use this plugin with `noStart: true`

**Actual Behaviour**

`start --migrate` fails with "Cannot create preexisting tables"

**Expected Behaviour**

create tables if they don't already exist, maybe warn if they do but don't fail

**LogCat for the issue**

```
Serverless: DynamoDB - Error - 
 
  Resource In Use Exception ------------------------------
 
  Cannot create preexisting table
```

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/83948/33775022-11d3fbb2-dc0b-11e7-858d-bca4419fa398.png)

**Would you like to work on the issue?**

if it's something you want this plugin to do, i'm happy to submit the fix. It's likely only a few lines of code

**Comment by rehrumesh** [comment]
@AshanFernando @mjzone what are your thoughts on this? I like the idea.

**Comment by AshanFernando** [comment]
+1 For this feature

**Comment by rehrumesh** [comment]
@mvayngrib Can you start working on this.

**Comment by rehrumesh** [comment]
Great work @mvayngrib Thank you very much. We will update the NPM soon.

**Comment by rehrumesh** [comment]
@AshanFernando
