### ISSUE TITLE
Suggestion: run only in some stages

### ISSUE THREAD

**Issue by kabo** [99xt/serverless-dynamodb-local#159]
I'm using serverless-offline to test things out locally. I've got stage `dev` for local dev, `test` for test environment, and `prod` for prod environment.

Running dynamodb-local in `dev` works as expected. But sometimes I want to test with the data in the test environment. But when I run serverless offline in stage test, dynamodb local still starts up. What's worse, it gives me an error and crashes. The error is `Cannot do operations on a non-existent table`.

Something like:
```yaml
  dynamodb:
    start:
      stages:
        - dev
```

would be really neat :)

**Comment by AshanFernando** [comment]
Thanks @kabo This is very useful. We have merged your PR.
