### ISSUE TITLE
Missing property error

### ISSUE THREAD

**Issue by gevorggalstyan** [99xt/serverless-dynamodb-local#176]
Serverless: DynamoDB - Error - 
 
  Unexpected Parameter -----------------------------------
 
  Unexpected key 'PointInTimeRecoverySpecification' found in params
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.11.2

**Comment by AshanFernando** [comment]
Thanks @gevorggalstyan We are looking into this.

**Comment by rehrumesh** [comment]
Fixed in #168
