### ISSUE TITLE
Dynamodb local download percentage goes beyond 100%

### ISSUE THREAD

**Issue by AshanFernando** [99xt/serverless-dynamodb-local#20]
Dynamodb local download percentage goes beyond 100% when running sls dynamodb start for the first time.

**Comment by rehrumesh** [comment]
![image](https://cloud.githubusercontent.com/assets/2035004/16005340/5dbaefa0-3184-11e6-8f30-5dae54ba8c2f.png)

**Comment by AshanFernando** [comment]
Completed :white_check_mark:
