### ISSUE TITLE
Deprecation warning: CLI options definitions were upgraded with "type" property

### ISSUE THREAD

**Issue by vladas** [99xt/serverless-dynamodb-local#268]
**Actual Behaviour**

When running sls, I get the following deprecation warning:

> Serverless: Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
>              - ServerlessDynamodbLocal for "online", "port", "cors", "inMemory", "dbPath", "sharedDb", "delayTransientStatuses", "optimizeDbBeforeStartup", "migrate", "seed", "migration", "heapInitial", "heapMax", "convertEmptyValues", "localPath"
>             Please report this issue in plugin issue tracker.
>             Starting with next major release, this will be communicated with a thrown error.
>             More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA

**Expected Behaviour**

No warning

**Steps to reproduce it**

     Operating System:          linux
     Node Version:              14.4.0
     Framework Version:         2.35.0 (standalone)
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.8.2

**Comment by flisboac** [comment]
Having the same issue.

EDIT: Nevermind, this plugin does NOT support Serverless@2, it's in the README. But will it support, someday?

**Comment by gabsn** [comment]
Still having this warning. Anyone taking care of it otherwise I can open the PR?

**Comment by RishikeshDarandale** [comment]
@AshanFernando , Can you please respond on roadmap about this plugin?

**Comment by wbruno** [comment]
we have to release this
https://github.com/99x/serverless-dynamodb-local/pull/267/files

**Comment by sleontribal** [comment]
Released 👍 #268

**Comment by medikoo** [comment]
Can someone close this issue?
