### ISSUE TITLE
Please deploy the new version that fixes the http -> https thing on the dynamodb-local package.

### ISSUE THREAD

**Issue by gabrielforster** [99xt/serverless-dynamodb-local#297]
**Actual Behaviour**

When installing the package it gets a error when downloading the "DynamoDBLocal.jar" from the url containg a http. Cause the dynamodb-local package uses a url with the https protocol.

**Expected Behaviour**

When installing the package it should install correctly and do not throw a error!

**Steps to reproduce it**

npm init -y and add this package to the dependencies list. Then run npm install

You guys actually have the fixed version. U just need to deploy it plssss

**Comment by domdomegg** [comment]
FYI: This package (`serverless-dynamodb-local`) doesn't appear to be maintained, with no new releases to NPM in over 2 years. Despite our pleas, I don't think this is getting deployed anytime soon.

**Solution:** You can use [serverless-dynamodb](https://www.npmjs.com/package/serverless-dynamodb), a maintained fork, instead. (Disclaimer: I am a contributor to this fork). It is a drop-in replacement for this package, and is updated to fix this bug. This is a drop-in replacement for `serverless-dynamodb-local`, so to upgrade simply:

1. Uninstall `serverless-dynamodb-local`, e.g. `npm uninstall serverless-dynamodb-local`
2. Install `serverless-dynamodb`, e.g. `npm install serverless-dynamodb`
3. Update references in your code, including your serverless config, from `serverless-dynamodb-local` to `serverless-dynamodb` (quite possible that you won't have any, as you just refer to it from your serverless config)
4. (optional) Update your serverless config custom `dynamodb` key to `serverless-dynamodb`

Of course, it's all still [open-source](https://github.com/raisenational/serverless-dynamodb) and MIT licensed. Ownership of this new package sits with a registered charity, that is committed to maintaining the package into the future and is open to contributions from the community.

There's [an explanation as to the intentions behind this fork, and how it compares to other forks in the README](https://github.com/raisenational/serverless-dynamodb#why-fork).

In any case would be open to feedback on the fork - can drop [create an issue in that repository](https://github.com/raisenational/serverless-dynamodb/issues/new) or email me (address on [profile](http://github.com/domdomegg)).
