### ISSUE TITLE
Implement other commands for dynamodb

### ISSUE THREAD

**Issue by AshanFernando** [99xt/serverless-dynamodb-local#3]
Currently only sls dynamodb launch is only implemented. Implement the following commands
- stop
- relaunch
Note: the basic logic for these functions are already implemented in dynamodb/db.js. The need is to create custom actions in root/index.js and call the relevant functions

**Comment by AshanFernando** [comment]
Completed :white_check_mark:

**Comment by wan54** [comment]
Hi there,

I'm on 0.2.36 and `stop` command is not supported. Which version does this command is supposed to be supported?

Thanks for your effort on this plugin.
