### ISSUE TITLE
Environment variables for table name

### ISSUE THREAD

**Issue by gwincr11** [99xt/serverless-dynamodb-local#42]
Hello,

Is there anyway to append env variables to the table names in migrations?

Thanks,
Cory

**Comment by AshanFernando** [comment]
At the moment there is no support for this. We can add this as a new feature for the next release. How about using a velocity parser for the json? Any suggestions?

**Comment by gwincr11** [comment]
You have the "table_prefix" "table_suffix" options, could you just pass in an option there to use the current env?

**Comment by gwincr11** [comment]
Or maybe just a simple thing like a migration flag that allowed the prefix to be passed in.

**Comment by AshanFernando** [comment]
Merged the PR with prefix and suffix variables.
