### ISSUE TITLE
Any serverless v1.0 support 

### ISSUE THREAD

**Issue by TaichiHo** [99xt/serverless-dynamodb-local#47]
I think the community is shifting towards serverless v1.0. Any support on that or do we have to use the native dynamodb local by aws?

**Comment by rehrumesh** [comment]
Hi @TaichiHo we are planing to complete the work on v1 soon. You can check the progress of V1 tree.
https://github.com/99xt/serverless-dynamodb-local/tree/v1

**Comment by TaichiHo** [comment]
Sorry I missed that. Thanks for the quick reply!
