### ISSUE TITLE
Cannot read property 'dynamodb' of null

### ISSUE THREAD

**Issue by ncherro** [99xt/serverless-dynamodb-local#49]
I installed the 1.0 branch following [instructions](https://github.com/99xt/serverless-dynamodb-local/tree/v1#install-plugin), but saw this error when trying to run `sls dyanmodb start`

```
  Type Error ---------------------------------------------
 
     Cannot read property 'dynamodb' of undefined
 
     For debugging logs, run again after setting SLS_DEBUG env var.
```

Debugging shows it comes from [this line](https://github.com/99xt/serverless-dynamodb-local/blob/v1/index.js#L197). I was able to get past the error by adding this to my `serverless.yml` file

```yaml
custom:
  dynamodb:
```

I'm a serverless noob - is it just a matter of updating the 1.0 branch README to reference `serverless.yml` instead of `s-project.json`?

**Comment by mjzone** [comment]
@ncherro You are absolutely correct. It should be added to the serverless.yml. We will fix the readme mistype immediately. Thank you for reporting this issue.

**Comment by jurosh** [comment]
it's probably not documented yet ? as I got same error now, after following installation steps..
