### ISSUE TITLE
Doesnt seem to ignore VIM .swp files

### ISSUE THREAD

**Issue by daviskoh** [99xt/serverless-dynamodb-local#50]
It seems that running migrations via `sls dynamodb executeAll` runs all files within /dynamodb regardless of whether they are .json extensions or not.

It may be useful to ignore non-json files. 

![image](https://cloud.githubusercontent.com/assets/5395403/19451689/f7b157a2-947b-11e6-8d10-e4acc83d64e9.png)

![image](https://cloud.githubusercontent.com/assets/5395403/19451761/10552626-947c-11e6-84f9-0f7249fd40c9.png)

Spec:
- serverless v1
- serverless-dynamodb-local v1

Steps to Reproduce:
- create migration file using `sls dynamodb create -n <filename>`
- open file using VIM or create `.<filename>.json.swp`
- run `sls dynamodb executeAll`

**Comment by Larry850806** [comment]
How to install the 'sls' command
I get 'command not found' when I use 'sls'

**Comment by rehrumesh** [comment]
@Larry850806 `sls` is an alias for `serverless`
If you have serverless installed properly, sls should work without any issue.

**Comment by AshanFernando** [comment]
@daviskoh Fixed the issue and deployed a new version(0.2.15) to npm.
