### ISSUE TITLE
Error "sls dynamodb install"

### ISSUE THREAD

**Issue by keita-nishimoto** [99xt/serverless-dynamodb-local#70]
When I ran ```sls dynamodb install``` an error message appeared as shown below.

Full stack trace:

```
[Error: Error getting DynamoDb local latest tar.gz location: 200]
/home/vagrant/aws-serverless-prototype/node_modules/dynamodb-localhost/dynamodb/installer.js:43
                    throw Error("Error in downloading Dynamodb local " + err);
                    ^

Error: Error in downloading Dynamodb local Error: connect ECONNREFUSED 127.0.0.1:80
    at Error (native)
    at ClientRequest.<anonymous> (/home/vagrant/aws-serverless-prototype/node_modules/dynamodb-localhost/dynamodb/installer.js:43:27)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:269:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1269:8)
    at nextTickCallbackWith2Args (node.js:458:9)
    at process._tickDomainCallback (node.js:413:17)
```

My operating environment is as follows.

- HostOS
  - MacOS Sierra 10.12.3
- GuestOS(Vagrant 1.8.7 + VirtualBOX 5.1.12)
  - CentOS Linux release 7.3.1611 (Core)
- Node.js(v4.7.2)
- serverless(1.5.1)
- serverless-dynamodb-local(0.2.16)

I did a bit of ```node_modules/dynamodb-localhost/dynamodb/installer.js``` debugging.

I could download from the URL stored in the variable "downloadUrl" on line 11 using curl.

```
$ curl -L -O -kv http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                               Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* About to connect() to dynamodb-local.s3-website-us-west-2.amazonaws.com port 80 (#0)
*   Trying 52.218.144.91...
* Connected to dynamodb-local.s3-website-us-west-2.amazonaws.com (52.218.144.91) port 80 (#0)
> GET /dynamodb_local_latest.tar.gz HTTP/1.1
> User-Agent: curl/7.29.0
> Host: dynamodb-local.s3-website-us-west-2.amazonaws.com
> Accept: */*
>
< HTTP/1.1 200 OK
< x-amz-id-2: I1DQB9usvczdpC6MXBB09f7rnkCHHEei4+QLjsI21YxluUraUfpYfU80ooIOWsadH3E7eKm+/z4=
< x-amz-request-id: 49C3FA2E3E3AADD0
< Date: Sun, 29 Jan 2017 12:25:40 GMT
< Last-Modified: Wed, 18 Jan 2017 18:26:45 GMT
< x-amz-version-id: wRzlbckhjnZIm0CVgcmTkkgmHBAB9l_U
< ETag: "c7c1bacf57b840022927f67d1a4b8e46"
< Content-Type: application/x-gzip
< Content-Length: 44203144
< Server: AmazonS3
<
{ [data not shown]
100 42.1M  100 42.1M    0     0  6133k      0  0:00:07  0:00:07 --:--:-- 8229k
* Connection #0 to host dynamodb-local.s3-website-us-west-2.amazonaws.com left intact
```

However, the contents of ```response.headers.location``` passed to ```http.get ()``` on line 16 was ```undefined```.

**Comment by IntegralOfZero** [comment]
serverless-dynamodb-local is currently locked into version 0.0.2 of dependency https://github.com/99xt/dynamodb-localhost which was recently updated. This issue should be resolved  once this is updated. I had tried applying the changes made to "installer.js" in https://github.com/99xt/dynamodb-localhost/commit/67fbde7d5fa15d860ebd884416de5aa06f0e5890 locally and I was able to get it to work, so the update should be all that's required to fix this.

**Comment by IntegralOfZero** [comment]
@AshanFernando I see that the commit https://github.com/99xt/serverless-dynamodb-local/commit/36b8e9c3b60c3f8eaf5335892205e5c58c6c34d5 in the v1 branch contains the updated version. Would it be possible to get this in as a hotfix on its own, or will that have undesirable impact that makes it better to wait until the v1 branch itself is ready?

**Comment by AshanFernando** [comment]
@IntegralOfZero v1 branch is already having its updated npm version which is 0.2.16 which is for serverless 1.5+. master branch contains plugin code for serverless 0.5. I have also added the latest version of dynamodb-localhost plugin to master branch

**Comment by constantpslalom** [comment]
@AshanFernando There exists version 0.2.17 of serverless-dynamodb-local. Running "npm install --save serverless-dynamodb-local" installs 0.2.16 which contains the updated dynamodb-local dependency (0.0.5), but then subsequently running "npm update --save serverless-dynamodb-local" updates it to 0.2.17 which contains the old dynamodb-local (0.0.2). I also tried 0.2.18 to see if that existed as well, but as expected it doesn't. I did see a list of all valid version targets in my output though:

`
npm ERR! notarget No compatible version found: serverless-dynamodb-local@^0.2.18
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.0.2, 1.0.1, 1.0.0, **0.2.17**, 0.2.16, 0.2.15, 0.2.14, 0.2.13, 0.2.12, 0.2.11, 0.2.10, 0.2.9, 0.2.8, 0.2.7, 0.2.6, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.1, 0.1.0, 0.0.10, 0.0.9, 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1
`

I switched the entry in my package.json from "serverless-dynamodb-local": "^0.2.17" back to "serverless-dynamodb-local": "^0.2.16", and it works as expected.

**Comment by IntegralOfZero** [comment]
@AshanFernando There exists version 0.2.17 of serverless-dynamodb-local. Running "npm install --save serverless-dynamodb-local" installs 0.2.16 which contains the updated dynamodb-local dependency (0.0.5), but then subsequently running "npm update --save serverless-dynamodb-local" updates it to 0.2.17 which contains the old dynamodb-local (0.0.2). I also tried 0.2.18 to see if that existed as well, but as expected it doesn't. I did see a list of all valid version targets in my output though:

npm ERR! notarget No compatible version found: serverless-dynamodb-local@^0.2.18
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.0.2, 1.0.1, 1.0.0, 0.2.17, 0.2.16, 0.2.15, 0.2.14, 0.2.13, 0.2.12, 0.2.11, 0.2.10, 0.2.9, 0.2.8, 0.2.7, 0.2.6, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.1, 0.1.0, 0.0.10, 0.0.9, 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1

I switched the entry in my package.json from "serverless-dynamodb-local": "^0.2.17" back to "serverless-dynamodb-local": "^0.2.16", and it works as expected.

**Comment by chamathpali** [comment]
Hi @IntegralOfZero i just tried out. I think there are few releases which are not monitored. better use the specific version. but you can use npm install --save serverless-dynamodb-local@latest to make sure its the correct version as in the npm registry

**Comment by AshanFernando** [comment]
@IntegralOfZero Thanks for pointing this out. I will see on how to solve this and do an update in npm registry.

**Comment by AshanFernando** [comment]
@IntegralOfZero New version of 0.2.18 is deployed to bypass 0.2.17 issue.

**Comment by IntegralOfZero** [comment]
@AshanFernando :thumbsup:
