### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by cbrammer** [99xt/serverless-dynamodb-local#81]
The current code state is not published to NPM. It took me a while to figure out why tables where not being created 😕   Ends up that the published version is out of date. Could you update to NPM please?

**Comment by AshanFernando** [comment]
I have sent a PR #82  with incremented NPM version to do the deployment. Can someone review and merge it for deployment.

**Comment by rehrumesh** [comment]
#82 is merged now. Closing the issue

**Comment by cbrammer** [comment]
That was fast! Thank you
